### ISSUE TITLE
Assignment2

### ISSUE THREAD

**Issue by IP-CAD** [goodboyanush/iiit-bangalore-march-april-2019#4]
To use GPU powered notebooks, I couldn't find option for that in the Environment tab.
Attaching the screenshot.
![Untitled](https://user-images.githubusercontent.com/46589972/56186617-9aecea00-603d-11e9-9a85-f347819e9318.png)

**Comment by goodboyanush** [comment]
Yes, I just found that GPU powered notebooks are not yet publicly available. It is expected to come soon. In the meantime, you have the following options
1. The cpu machines are pretty good in notebook. You can run in the cpu machines
2. Use neural network modeler. Through which you can run your code in GPU.
3. Write the code locally and submit an 'experiment'. You should get good documentation on how to do this.

**Comment by IP-CAD** [comment]
> Yes, I just found that GPU powered notebooks are not yet publicly available. It is expected to come soon. In the meantime, you have the following options
> 
> 1. The cpu machines are pretty good in notebook. You can run in the cpu machines
> 2. Use neural network modeler. Through which you can run your code in GPU.
> 3. Write the code locally and submit an 'experiment'. You should get good documentation on how to do this.

Thanks. Will check that.

**Comment by IP-CAD** [comment]
Hi,
Using 'experiment', the available frameworks to build the model is tensorflow, pytorch and caffe. Couldn't find Keras.

**Comment by goodboyanush** [comment]
Hi Keras is supported. See here: https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/pm_service_supported_frameworks.html#supported-deep-learning-frameworks

Also, see some examples here: 
1. https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/xs-overview.html?linkInPage=true
2. https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/ml_dlaas_e2e_example.html
3. https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/ml_dlaas_code_guidelines.html

**Comment by goodboyanush** [comment]
@ammuvikas  Please check #6
