### ISSUE TITLE
Assignment 2 - Pre trained weights

### ISSUE THREAD

**Issue by progvasu** [goodboyanush/iiit-bangalore-march-april-2019#5]
Hi Anush,

Just a small clarification needed. 

Are we allowed to use the pre-trained weights for the Inception V3 network (weights for imagenet dataset are available in keras) and do transfer learning -or- should we just use the architecture and train the model from scratch.

**Comment by goodboyanush** [comment]
@progvasu I would highly recommend that you use the pre-trained ImageNet weights available in Keras. Training for scratch would be a nightmare without enough GPU computation.

**Comment by progvasu** [comment]
Thanks! @goodboyanush will use the pre-trained weights

**Comment by goodboyanush** [comment]
@progvasu  Please check Issue #6
