### ISSUE TITLE
Assignment 3 Question 1

### ISSUE THREAD

**Issue by snigdha1292** [goodboyanush/iiit-bangalore-march-april-2019#9]
For the question 1, I do not understand the binary classification part.
What I understand is that we do face recognition using CNN and then at test time pick two images and classify them to the two classes by either checking the labels or through some distance metrics and using threshold on the features extracted. Is my understanding right?

**Comment by goodboyanush** [comment]
@snigdha1292 
There are two types of Face Comparison:
1. Face Recognition: Given one face image, identify who that person is?
2. Face Verification: Given two face images, identify if they belong to the same person or not? I need not know who that person is, but only if they belong to the same person. Hence it is binary classification: belonging to the same person or not belonging to the same person.

Hence, during both training and testing time, the input to your deep learning model, will be two images. And the deep learning model will perform binary classification.
